### ISSUE TITLE
make a html page which display's a table with column as name, age , field of intrest , github profile

### ISSUE THREAD

**Issue by Ap12saga** [Ap12saga/Website-Hacktober#1]

**Comment by theopaid** [comment]
Hi! Assign the issue to me and i'll make a PR on Oct 1st :)

**Comment by Ap12saga** [comment]
ok @theopaid I will Assign you :+1:

**Comment by purnima143** [comment]
Can I work on this project, if the issue is not solved yet

**Comment by theopaid** [comment]
> Can I work on this project, if the issue is not solved yet

Sure, go ahead.
